---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloud-controller-manager
  labels:
    k8s-app: cloud-controller-manager
spec:
  selector:
    matchLabels:
      k8s-app: cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: cloud-controller-manager
    spec:
      hostNetwork: true
      dnsPolicy: Default
      serviceAccountName: cloud-controller-manager
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
        - image: controller:latest
          name: cloud-controller-manager
          command:
            - /manager
            - --cloud-provider=onmetal
            - --cloud-config=/app/config.yaml
            - --v=3
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          volumeMounts:
            - name: "onmetal-ccm-pvc"
              mountPath: "/app/config.yaml"
              subPath: "config.yaml"
      volumes:
        - name: "onmetal-ccm-pvc"
          secret:
            secretName: "onmetal-ccm"