apiVersion: apps/v1
kind: Deployment
metadata:
  name: onmetal-cloud-controller-manager
  labels:
    k8s-app: onmetal-cloud-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: onmetal-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: onmetal-cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      containers:
        - name: manager
          command:
            - /bin/onmetal-cloud-provider-manager
          args:
            - --cloud-provider=onmetal
            - --cloud-config=/etc/cloud/cloud-config
            - --onmetal-kubeconfig=/etc/onmetal/kubeconfig
            - --kubeconfig=/etc/kubernetes/kubeconfig
            - --authentication-kubeconfig=/etc/kubernetes/kubeconfig
            - --authorization-kubeconfig=/etc/kubernetes/kubeconfig
            - --use-service-account-credentials
            - --leader-elect=true
            - --v=2
          image: controller:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: kubeconfig
              readOnly: true
            - mountPath: /etc/onmetal
              name: onmetalkubeconfig
              readOnly: true
            - mountPath: /etc/cloud
              name: cloud-config
              readOnly: true
      volumes:
        - secret:
            secretName: cloud-config
            items:
              - key: cloud-config
                path: cloud-config
          name: cloud-config
        - secret:
            secretName: kubeconfig
          name: kubeconfig
        - secret:
            secretName: onmetalkubeconfig
          name: onmetalkubeconfig
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
