apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: occm
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
