apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: ironcore-cloud-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never